# Generated by Django 3.2 on 2023-11-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.BigIntegerField(verbose_name='Price')),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('is_enable', models.BooleanField(default=True, verbose_name='is enable')),
                ('uniqe_code', models.PositiveIntegerField(unique=True, verbose_name='uniqe_code')),
                ('categories', models.ManyToManyField(to='Category.Category', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
    ]
