# Generated by Django 3.2 on 2023-09-03 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.BigIntegerField(verbose_name='Price')),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('is_enable', models.BooleanField(default=True, verbose_name='is enable')),
                ('uniqe_code', models.PositiveIntegerField(unique=True, verbose_name='uniqe_code')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
    ]
