# Generated by Django 3.2 on 2023-11-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
