# Generated by Django 3.2 on 2023-09-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
        ('Product', '0002_alter_products_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ManyToManyField(to='Category.Category', verbose_name='categories'),
        ),
    ]
