# Generated by Django 3.2 on 2023-11-14 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_active_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='valid_end_discount',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='valid_from_discount',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
