# Generated by Django 3.2 on 2023-11-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20231114_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_active_discount',
        ),
        migrations.RemoveField(
            model_name='products',
            name='valid_end_discount',
        ),
        migrations.RemoveField(
            model_name='products',
            name='valid_from_discount',
        ),
    ]
