# Generated by Django 3.2 on 2023-11-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20231114_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_dis',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قیمت ویژه'),
        ),
    ]
