# Generated by Django 3.2 on 2023-11-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_products_price_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price_dis',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='قیمت ویژه'),
        ),
    ]
