# Generated by Django 3.2 on 2023-11-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_products_price_dis'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='has_discount',
            field=models.BooleanField(default=False),
        ),
    ]
