# Generated by Django 3.2 on 2023-11-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_products_has_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='دارای تخفیف'),
        ),
    ]
