# Generated by Django 3.2 on 2023-11-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostFiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article_File',
        ),
    ]
