# Generated by Django 3.2 on 2023-11-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('text', models.TextField(blank=True, null=True, verbose_name='بدنه مقاله')),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('uniqe_code', models.PositiveIntegerField(unique=True, verbose_name='uniqe_code')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'Articles',
            },
        ),
    ]
