# Generated by Django 3.2 on 2023-11-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_article_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=256, verbose_name='عنوان'),
        ),
    ]
