# Generated by Django 3.2 on 2023-11-12 08:49

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0005_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
