# Generated by Django 3.2 on 2023-11-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
