# Generated by Django 3.2 on 2023-11-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='valid_end_discount',
            field=models.DateField(blank=True, null=True, verbose_name='پایان تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_from_discount',
            field=models.DateField(blank=True, null=True, verbose_name='شروع تخفیف'),
        ),
    ]
