# Generated by Django 3.2 on 2023-11-14 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0002_auto_20231114_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_end_discount',
            field=models.DateTimeField(verbose_name='پایان تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_from_discount',
            field=models.DateTimeField(default=None, verbose_name='شروع تخفیف'),
            preserve_default=False,
        ),
    ]
